# Generated by Django 4.1 on 2022-08-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detailed_sale',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_description', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('Money', 'Dinheiro'), ('Credit', 'Credito'), ('Debit', 'Debito'), ('Pix', 'Pix')], max_length=8)),
                ('card_info', models.CharField(max_length=16)),
                ('sela_data', models.DateField(auto_now=True)),
            ],
        ),
    ]
